/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FilterSelect: typeof import('./components/molecules/FilterSelect.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PageHeader: typeof import('./components/organisms/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceActionsMenu: typeof import('./components/molecules/ServiceActionsMenu.vue')['default']
    ServiceAvatar: typeof import('./components/atoms/ServiceAvatar.vue')['default']
    ServiceCard: typeof import('./components/molecules/ServiceCard.vue')['default']
    ServiceCreateForm: typeof import('./components/organisms/ServiceCreateForm.vue')['default']
    ServiceEditDialog: typeof import('./components/organisms/ServiceEditDialog.vue')['default']
    ServiceFilters: typeof import('./components/organisms/ServiceFilters.vue')['default']
    ServiceList: typeof import('./components/organisms/ServiceList.vue')['default']
    StatusBadge: typeof import('./components/atoms/StatusBadge.vue')['default']
    TypeIcon: typeof import('./components/atoms/TypeIcon.vue')['default']
  }
}
